name: Test Secret Configuration

on:
  workflow_dispatch:  # 手動実行専用

jobs:
  test-secret:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check LINE Messaging API secrets exist
        env:
          ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          USER_ID: ${{ secrets.LINE_TARGET_USER_ID }}
        run: |
          EXIT_CODE=0

          if [ -z "$ACCESS_TOKEN" ]; then
            echo "❌ LINE_CHANNEL_ACCESS_TOKEN is not set"
            echo "Please add LINE_CHANNEL_ACCESS_TOKEN to GitHub Secrets"
            echo "Settings → Secrets and variables → Actions → New repository secret"
            EXIT_CODE=1
          else
            echo "✅ LINE_CHANNEL_ACCESS_TOKEN is set (length: ${#ACCESS_TOKEN} characters)"
          fi

          if [ -z "$USER_ID" ]; then
            echo "❌ LINE_TARGET_USER_ID is not set"
            echo "Please add LINE_TARGET_USER_ID to GitHub Secrets"
            echo "Settings → Secrets and variables → Actions → New repository secret"
            EXIT_CODE=1
          else
            echo "✅ LINE_TARGET_USER_ID is set (length: ${#USER_ID} characters)"
          fi

          exit $EXIT_CODE

      - name: Test LINE Messaging API integration
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_USER_ID: ${{ secrets.LINE_TARGET_USER_ID }}
        run: |
          cd src
          python notify_line.py
