name: Test Secret Configuration

on:
  workflow_dispatch:  # 手動実行専用

jobs:
  test-secret:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check LINE_NOTIFY_TOKEN exists
        env:
          TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "❌ LINE_NOTIFY_TOKEN is not set"
            echo "Please add LINE_NOTIFY_TOKEN to GitHub Secrets"
            echo "Settings → Secrets and variables → Actions → New repository secret"
            exit 1
          else
            echo "✅ LINE_NOTIFY_TOKEN is set (length: ${#TOKEN} characters)"
          fi

      - name: Test LINE Notify integration
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: |
          cd src
          python notify_line.py
